---
version: 1
service:
  name: portainer
  lifecycle:
  tier: tier_3
  product: Observability
  owner: devops
  system: prod_eks_cluster
  language: YAML
  framework: Helmchart
  description: This is for our observability dashboards
  aliases:
  - k8s:portainer-portainer
  repositories:
  - name: devopsjourney1/homelab-services
    path: "/k8s/portainer"
    provider: github
  tools:
  - name: PagerDuty
    category: incidents
    url: https://bigriver.pagerduty.com/services/BWA23IT
    environment: Production
  - name: Splunk
    category: logs
    url: http://www.splunk.com/url
    environment:
  - name: Confluence
    category: wiki
    url: https://devopsbrad.atlassian.net/wiki/spaces/KB/pages/66004/portainer
    environment:
  - name: ArgoCD
    category: GitOps
    url: https://argocd.devopsbrad.com/applications/argocd/portainer
    environment:
  - name: Kuma
    category: health_checks
    url: https://kuma.devopsbrad.com/dashboard/9
    environment:
  - name: Datadog
    category: metrics
    url: https://datadog.com/dashboard
    environment:
  - name: Kubernetes
    category: orchestrator
    url: https://deploy.bigriver.com/catalog
    environment:
  dependencies:
  - alias: 
  alert_sources: