http:
  routers:
    argocd-router:
      rule: "Host(`argocd.devopsbrad.com`)"
      service: argocd-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsEncrypt-production

  services:
    argocd-service:
      loadBalancer:
        servers:
          - url: "http://192.168.0.145"

