http:
  routers:
    tplink-router:
      rule: "Host(`router.devopsbrad.com`)"
      service: tplink-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsEncrypt-production

  services:
    tplink-service:
      loadBalancer:
        servers:
          - url: "http://192.168.0.1"
