http:
  routers:
    grafana-router:
      rule: "Host(`grafana.devopsbrad.com`)"
      service: grafana-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsEncrypt-production

  services:
    grafana-service:
      loadBalancer:
        servers:
          - url: "http://192.168.0.100"