http:
  routers:
    router:
      rule: "Host(`proxmox.devopsbrad.com`)"
      service: proxmox-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsEncrypt-production

  services:
    router-service:
      loadBalancer:
        servers:
          - url: "http://192.168.0.100:8006"
