apiVersion: v2
name: jenkins
description: My Custom Jenkins Chart

type: application

version: 0.1.0

appVersion: 2.401.3

dependencies:
  - name: jenkins
    version: 4.4.2
    repository: https://charts.jenkins.io/