apiVersion: v2
name: cilium
displayName: Cilium
home: https://cilium.io/
version: 1.13.90
appVersion: 1.13.90
kubeVersion: ">= 1.16.0-0"
icon: https://cdn.jsdelivr.net/gh/cilium/cilium@main/Documentation/images/logo-solo.svg
description: eBPF-based Networking, Security, and Observability
keywords:
  - BPF
  - eBPF
  - Kubernetes
  - Networking
  - Security
  - Observability
  - Troubleshooting
sources:
  - https://github.com/cilium/cilium
