apiVersion: v2
name: cilium-custom
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: 1.13.2

dependencies:
  - name: cilium
    version: 1.13.2
    repository: https://helm.cilium.io/