#https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
cilium:
  localRedirectPolicy: true
  kubeProxyReplacement: true
  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - "hubble.devopsbrad.com"
    metrics:
      enableOpenMetrics: true
      enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
  operator:
    replicas: 1
    prometheus:
      enabled: true
      port: 9966
  prometheus:
    enabled: true
    port: 9962
