#https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
cilium:
  localRedirectPolicy: true
  kubeProxyReplacement: true
  operator:
    prometheus:
      enabled: true
      port: 9966
  prometheus:
    enabled: true
    port: 9962