global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  filePath: /traefik/logs/traefik.log

accessLog:
  filePath: /traefik/logs/traefik-access.log

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: metrics

entryPoints:
  web:
    address: ":8000"
    http:
      redirections:                           # HTTPS redirection (80 to 443)
        entryPoint:
          to: "websecure"                         # The target element
          scheme: "https"                        # The redirection target scheme
          permanent: true
  websecure:
    address: ":8443"
  metrics:
    address: ":9091"

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    exposedByDefault: false
    swarmMode: false
  file:
    directory: "/etc/traefik/conf"
    watch: true
  providersThrottleDuration: "10"

certificatesResolvers:
  letsEncrypt-staging:
    acme:
      email: bradmorg@gmail.com
      storage: "/etc/traefik/certs/acme.json"
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

  letsEncrypt-production:
    acme:
      email: bradmorg@gmail.com
      storage: "/etc/traefik/certs/acme.json"
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
