coredns:
  replicaCount: 2
  prometheus:
    service:
      enabled: true
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9153"
  service:
    clusterIP: "10.43.0.10"