---
apiVersion: v2
name: kube-prometheus-stack
description: My Custom Prometheus Helm Chart

type: application

dependencies:
  - name: kube-prometheus-stack
    version: 0.69.1
    repository: https://prometheus-community.github.io/helm-charts