kube-prometheus-stack:
  kube-state-metrics:

  alertmanager:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - alerts.devopsbrad.com
      tls:
        - secretName: alertmanager-server-tls
          hosts:
            - alerts.devopsbrad.com

  grafana:
    enabled: true
    adminPassword: prom-operator
    ingress:
      enabled: true
      hosts:
        - grafana.devopsbrad.com
      tls:
        - secretName: grafana-server-tls
          hosts:
            - grafana.devopsbrad.com

  prometheus:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - prom.devopsbrad.com
      tls:
        - secretName: prometheus-server-tls
          hosts:
            - prom.devopsbrad.com
