version: '3'
services:
  tailscale:
    container_name: tailscaled
    hostname: tailscaled
    volumes:
        - tailscale:/var/lib/tailscale
        - /dev/net/tun:/dev/net/tun
    network_mode: host
    environment:
        - TS_ROUTES=$SUBNET
        - TS_STATE=/var/lib/tailscale/tailscaled.state
        - TS_STATE_DIR=/var/lib/tailscale/
    image: tailscale/tailscale:stable
    restart: unless-stopped

volumes:
  tailscale:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/tailscale'
  kuma-storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/kuma'