apiVersion: v2
name: argo-cd
description: My Custom ArgoCD Helm Chart

type: application

version: 0.1.0

dependencies:
  - name: argo-cd
    version: 5.51.1
    repository: https://argoproj.github.io/argo-helm