apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  destination:
    name: ''
    namespace: cilium
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/cilium
  sources: []
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
