apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium
  namespace: cilium
spec:
  generators:
  - list:
      elements:
      - cluster: k3s
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-cilium'
    spec:
      project: default
      source:
        repoURL: https://github.com/devopsjourney1/homelab-services.git
        path: k8s/cilium
        targetRevision: HEAD
        helm:
          releaseName: '{{cluster}}-cilium'
      destination:
        server: '{{url}}'
        namespace: cilium
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-ingress
  namespace: default
spec:
  generators:
  - list:
      elements:
      - cluster: k3s
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-ingress'
    spec:
      project: default
      source:
        repoURL: https://github.com/devopsjourney1/homelab-services.git
        path: k8s/argocd
        targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
    kind: Ingress
    path: argo-ingress.yaml