apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-upgrades
spec:
  destination:
    namespace: system-upgrade
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/k3s
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/cilium
    helm:
      valueFiles:
        - values.yaml
  # syncPolicy:
  #   automated: {}
  #   syncOptions:
  #   - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/argocd
    helm:
      valueFiles:
        - values.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/prometheus
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/grafana
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: 'ingress.enabled'
          value: "true"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/coredns
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: fullnameOverride
          value: coredns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
spec:
  destination:
    namespace: portainer
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/portainer
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/argo-rollouts
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/argo-workflows
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
spec:
  destination:
    namespace: argocd-image-updater
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:devopsjourney1/homelab-services.git'
    targetRevision: HEAD
    path: k8s/argocd-image-updater
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true