apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k3s-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: k3s
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-cilium'
    spec:
      project: default
      source:
        repoURL: https://github.com/devopsjourney1/homelab-services.git
        path: k8s/cilium
        targetRevision: HEAD
        helm:
          releaseName: '{{cluster}}-cilium'
      destination:
        server: '{{url}}'
        namespace: guestbook
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true