---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Services:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.local:8096/
        description: Media Server
    - Sunshine:
        icon: sunshine.svg
        href: https://localhost:47990/
        description: Desktop Game Streaming
    - Passbolt:
        icon: passbolt.svg
        href: https://pass.devopsbrad.com/
        description: Password Manager
    - HomeAssistant:
        icon: home-assistant.svg
        href: http://home.devopsbrad.com:8123/
        description: Home automation

- Management:
    - Portainer:
        icon: portainer.png
        href: https://portainer.devopsbrad.com/
        description: Container Management
    - ArgoCD:
        icon: argocd.png
        href: https://argocd.devopsbrad.com/
        description: GitOps for Kubernetes
    - ArgoRollouts:
        icon: argocd.png
        href: http://rollouts.devopsbrad.com/rollouts/argo-rollouts
        description: Progressive Deployments
    - Teleport:
        icon: teleport.png
        href: https://tele.devopsbrad.com/
        description: SSH Session Manager


- Storage:
    - DSM:
        icon: synology-dsm.svg
        href: https://argocd.devopsbrad.com/
        description: Synology DSM
    - Drive:
        icon: https://cdn-icons-png.flaticon.com/512/2004/2004726.png
        href: https://192.168.0.172:5001/?launchApp=SYNO.SDS.Drive.Application
        description: Synology Drive
    - Photos:
        icon: https://cdn-icons-png.flaticon.com/512/337/337948.png
        href: https://192.168.0.172:5001/webman/3rdparty/SurveillanceStation/
        description: Synology Surveillance Station
    - Surveillance:
        icon: https://cdn-icons-png.flaticon.com/512/2642/2642651.png
        href: https://192.168.0.172:5001/webman/3rdparty/SurveillanceStation/
        description: Synology Surveillance Station

- Network:
    - Traefik:
        icon: traefik.png
        href: https://traefik.devopsbrad.com/dashboard
        description: Proxy Services
    - PIHole:
        icon: pi-hole.svg
        href: https://pihole.devopsbrad.com/admin/login.php
        description: DNS Sinkhole
    - Twingate:
        icon: twingate.svg
        href: https://bradhomelab.twingate.com
        description: Zero-trust Access VPN
    - Tailscale:
        icon: tailscale.svg
        href: https://login.tailscale.com/admin/machines
        description: Zero-trust Access VPN
    - Router:
        icon: router.svg
        href: https://router.devopsbrad.com/
        description: WiFi Router

- Observability:
    - Kuma:
        icon: uptime-kuma.svg
        href: https://kuma.devopsbrad.com/dashboard
        description: Service Status Dashboard
    - Grafana:
        icon: grafana.png
        href: https://grafana.devopsbrad.com/
        description: Grafana Dashboard
    - Prometheus:
        icon: prometheus.png
        href: https://prom.devopsbrad.com/
        description: Prometheus Metrics